trigger:
  batch: true
  branches:
    include:
      - main
      - feature/**
      - hotfix/**

pr:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

variables:
  projects: "**/Blogsphere.Notification.Service.csproj"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"
  dotnetVersion: "8.x"
  githubConnection: "github.com_sharthak1095"
  repositoryName: "Scaler-io/Blogsphere.Notification.Service"
  imageName: "sharthak1995/blogsphere.notification.svc"
  containerRegistry: "docker-hub-sharthak1995-connection"

stages:
  - stage: Build
    displayName: "Build Notification Service"
    jobs:
      - job: build
        displayName: "Build Job"
        steps:
          - template: build/build.yml
            parameters:
              projects: $(projects)
              buildPlatform: $(buildPlatform)
              buildConfiguration: $(buildConfiguration)
              dotnetVersion: $(dotnetVersion)
