version: "3.8"

services:
  notificationDb:
    container_name: notificationDb
    volumes:
      - notificationDb_data:/var/opt/mssql
    environment:
      - MSSQL_PID=Express
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y
    ports:
      - 1434:1433
    networks:
      - blogsphere_dev_net
