parameters:
  - name: imageName
    default: ""
  - name: tag
    default: ""
  - name: containerRegistry
    default: ""

steps:
  - checkout: self
  - task: Docker@2
    displayName: "Login to Docker Hub"
    inputs:
      command: "login"
      containerRegistry: ${{ parameters.containerRegistry }}

  - task: Docker@2
    displayName: "Build Docker Image"
    inputs:
      command: "build"
      Dockerfile: "$(Build.SourcesDirectory)/src/Blogsphere.Notification.Service/Dockerfile"
      buildContext: "$(Build.SourcesDirectory)/src/."
      repository: ${{ parameters.imageName }}
      tags: "${{ parameters.tag }}"

  - task: Docker@2
    displayName: "Push Docker Image"
    inputs:
      command: "push"
      repository: ${{ parameters.imageName }}
      tags: "${{ parameters.tag }}"
