version: "3.8"

services:
  blogsphere.notification.service:
    image: ${DOCKER_REGISTRY-}blogspherenotificationservice
    build:
      context: .
      dockerfile: Blogsphere.Notification.Service/Dockerfile

  notificationDb:
    image: mcr.microsoft.com/mssql/server:2022-latest

networks:
  blogsphere_dev_net:
    external: true

volumes:
  notificationDb_data:
