version: "3.8"

services:
  blogspherenfstrg:
    container_name: blogspherenfstrg
    ports:
      - "21000:10000" # Blob Storage
      - "21001:10001" # Queue Storage
      - "21002:10002" # Table Storage
    environment:
      - "AZURITE_ACCOUNTS=blogspherenfstrg:123e4567e89b12d3a456426614174000"
    volumes:
      - blogspherenfstrg_data:/data
    command: >
      azurite
       --location /data
       --loose
       --blobHost 0.0.0.0 --blobPort 10000
       --queueHost 0.0.0.0 --queuePort 10001
       --tableHost 0.0.0.0 --tablePort 10002
    restart: unless-stopped
    networks:
      - blogsphere_dev_net

  blogsphere.notification.service:
    container_name: Blogsphere.Notification.Service
    depends_on:
      - blogspherenfstrg
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - "Logging__LogOutputTemplate=[{Timestamp:dd-MM-yyyy HH:mm:ss, fff}] {Level} {Properties} [CorrelationId:{CorrelationId}] [Machine: {MachineName}] {CallerType}:{MemberName} {Message}{NewLine}{Exception}{NewLine}"
      - Logging__Console__Enabled=true
      - Logging__Console__LogLevel=Debug
      - Logging__Elastic__Enabled=true
      - Logging__Elastic__LogLevel=Debug
      - AppConfigurations__ApplicationIdentifier=Blogsphere.Notification.Service
      - AppConfigurations__ApplicationEnvironment=Docker
      - AppConfigurations__NotificationProcessInterval=30
      - AppConfigurations__IntervalUnit=ss
      - InfrastructureSettings__identityBaseUrl=http://localhost:5000
      - Elasticsearch__Uri=http://elasticsearch:9200
      - EventBus__Host=rabbitmq
      - EventBus__Username=guest
      - EventBus__Password=${RABBITMQ_PASSWORD}
      - EventBus__VirtualHost=/
      - ErrorQueueReprocessor__Enabled=true
      - ErrorQueueReprocessor__PollIntervalSeconds=30
      - ErrorQueueReprocessor__MaxAttempts=2
      - ErrorQueueReprocessor__ErrorQueues=[auth-code-sent_error,user-invitation-sent_error,password-reset-instruction-sent_error,management-user-welcome-email-sent_error,management-user-password-email-sent_error]
      - EmailTemplates__UserInvite=UserInvitationSent
      - EmailTemplates__AuthCodeSent=AuthCodeSent
      - EmailTemplates__PasswordResetInstructionSent=PasswordResetInstructionSent
      - EmailSettings__Server=sandbox.smtp.mailtrap.io
      - EmailSettings__Port=587
      - EmailSettings__CompanyAddress=support@blogsphere
      - EmailSettings__UserName=${EMAIL_USERNAME}
      - EmailSettings__Password=${EMAIL_PASSWORD}  
      - ConnectionStrings__AzureTableStorage=${CONNECTION_STRING_AZURE_TABLE_STORAGE}
      - ConnectionStrings__BlobStorage=${CONNECTION_STRING_BLOB_STORAGE}
      - Zipkin__Url=http://zipkin:9411/api/v2/spans
      - Jaeger__Host=jaeger
      - Jaeger__Port=6831
    networks:
      - blogsphere_dev_net
