version: "3.8"

services:
  blogsphere.notification.service:
    image: ${DOCKER_REGISTRY-}blogspherenotificationservice
    build:
      context: .
      dockerfile: Blogsphere.Notification.Service/Dockerfile

  blogspherenfstrg:
    image: mcr.microsoft.com/azure-storage/azurite:latest

networks:
  blogsphere_dev_net:
    external: true

volumes:
  blogspherenfstrg_data: