version: "3.8"

services:
  notificationDb:
    container_name: notificationDb
    volumes:
      - notificationDb_data:/var/opt/mssql
    environment:
      - MSSQL_PID=Express
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y
    ports:
      - 1434:1433
    networks:
      - blogsphere_dev_net

  blogsphere.notification.service:
    container_name: Blogsphere.Notification.Service
    depends_on:
      - notificationDb
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - "Logging__LogOutputTemplate=[{Timestamp:dd-MM-yyyy HH:mm:ss, fff}] {Level} {Properties} [CorrelationId:{CorrelationId}] [Machine: {MachineName}] {CallerType}:{MemberName} {Message}{NewLine}{Exception}{NewLine}"
      - Logging__Console__Enabled=true
      - Logging__Console__LogLevel=Debug
      - Logging__Elastic__Enabled=true
      - Logging__Elastic__LogLevel=Debug
      - AppConfigurations__ApplicationIdentifier=Blogsphere.Notification.Service
      - AppConfigurations__ApplicationEnvironment=Docker
      - AppConfigurations__NotificationProcessInterval=30
      - AppConfigurations__IntervalUnit=ss
      - InfrastructureSettings__identityBaseUrl=http://localhost:5000
      - Elasticsearch__Uri=http://elasticsearch:9200
      - EventBus__Host=rabbitmq
      - EventBus__Username=guest
      - EventBus__Password=${RABBITMQ_PASSWORD}
      - EventBus__VirtualHost=/
      - EmailTemplates__UserInvite=UserInvitationSent
      - EmailTemplates__AuthCodeSent=AuthCodeSent
      - EmailTemplates__PasswordResetInstructionSent=PasswordResetInstructionSent 
      - EmailSettings__Server=sandbox.smtp.mailtrap.io
      - EmailSettings__Port=587
      - EmailSettings__CompanyAddress=support@blogsphere
      - EmailSettings__UserName=${EMAIL_USERNAME}
      - EmailSettings__Password=${EMAIL_PASSWORD}  
      - ConnectionStrings__AzureTableStorage=${CONNECTION_STRING_AZURE_TABLE_STORAGE}
      - ConnectionStrings__BlobStorage=${CONNECTION_STRING_BLOB_STORAGE}
      - Zipkin__Url=http://zipkin:9411/api/v2/spans
      - Jaeger__Host=jaeger
      - Jaeger__Port=6831
    networks:
      - blogsphere_dev_net
